-- 035：把未分类留存表扩成可按 run/SPU 对账的 v3 终态账。
--
-- 旧表以 (message_id, seq, week) 为主键，会把同一事实扇出到多个 SPU 的
-- 终态折叠成一行。本迁移保留全部旧行（旧行 run_id/assigned_spu 为 NULL），
-- 只把新运行的幂等粒度改为冻结快照键。
BEGIN;

SET LOCAL search_path = public, pg_temp;

DO $guard$
BEGIN
  IF current_user <> 'voc_admin' THEN
    RAISE EXCEPTION '035 必须以 voc_admin 执行，当前为 %', current_user;
  END IF;
END
$guard$;

ALTER TABLE public.voc_unclassified_evidence
  ADD COLUMN IF NOT EXISTS terminal_id bigint
    GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS run_id text,
  ADD COLUMN IF NOT EXISTS assigned_spu text;

-- 旧复合主键不能表达 fan-out；换成纯技术主键，原业务键由下面两套唯一键
-- 分别保护。已有行在 ADD IDENTITY 时取得 terminal_id，不做 DELETE/UPDATE。
DO $primary_key$
DECLARE
  pk_name text;
  pk_columns text[];
BEGIN
  SELECT c.conname,
         array_agg(a.attname ORDER BY u.ord)
    INTO pk_name, pk_columns
    FROM pg_constraint c
    CROSS JOIN LATERAL unnest(c.conkey)
      WITH ORDINALITY AS u(attnum, ord)
    JOIN pg_attribute a
      ON a.attrelid = c.conrelid AND a.attnum = u.attnum
   WHERE c.conrelid = 'public.voc_unclassified_evidence'::regclass
     AND c.contype = 'p'
   GROUP BY c.conname;

  IF pk_columns = ARRAY['message_id', 'seq', 'week']::text[] THEN
    EXECUTE format(
      'ALTER TABLE public.voc_unclassified_evidence DROP CONSTRAINT %I',
      pk_name);
    ALTER TABLE public.voc_unclassified_evidence
      ADD CONSTRAINT voc_unclassified_evidence_pkey
      PRIMARY KEY (terminal_id);
  ELSIF pk_columns IS NULL THEN
    ALTER TABLE public.voc_unclassified_evidence
      ADD CONSTRAINT voc_unclassified_evidence_pkey
      PRIMARY KEY (terminal_id);
  ELSIF pk_columns IS DISTINCT FROM ARRAY['terminal_id']::text[] THEN
    RAISE EXCEPTION '035 遇到未知主键形状：%', pk_columns;
  END IF;
END
$primary_key$;

-- 001 的旧 CHECK 只允许三种 Stage1 终态；v3 还必须逐组记录生成失败与
-- grounding 拒绝。旧行 reason 原值全部在新枚举内。
ALTER TABLE public.voc_unclassified_evidence
  DROP CONSTRAINT IF EXISTS voc_unclassified_evidence_reason_check;

DO $constraints$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.voc_unclassified_evidence'::regclass
       AND conname = 'ck_terminal_reason'
  ) THEN
    ALTER TABLE public.voc_unclassified_evidence
      ADD CONSTRAINT ck_terminal_reason CHECK (
        reason IS NULL OR reason IN (
          'unclassified', 'vote_dropped', 'truncated',
          'generation_failed', 'grounding_rejected'
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.voc_unclassified_evidence'::regclass
       AND conname = 'ck_terminal_run_assignment_pair'
  ) THEN
    ALTER TABLE public.voc_unclassified_evidence
      ADD CONSTRAINT ck_terminal_run_assignment_pair CHECK (
        (run_id IS NULL) = (assigned_spu IS NULL)
        AND (run_id IS NULL OR NULLIF(btrim(run_id), '') IS NOT NULL)
        AND (assigned_spu IS NULL
             OR NULLIF(btrim(assigned_spu), '') IS NOT NULL)
        AND (run_id IS NULL OR reason IS NOT NULL)
      );
  END IF;

  -- 普通 UNIQUE 允许旧行的 NULL run_id 共存；所有 v3 行四列均非 NULL，
  -- 因而正好是一条快照扇出键一条终态，可供 ON CONFLICT 幂等更新原因。
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.voc_unclassified_evidence'::regclass
       AND conname = 'uq_terminal_run_key'
  ) THEN
    ALTER TABLE public.voc_unclassified_evidence
      ADD CONSTRAINT uq_terminal_run_key
      UNIQUE (run_id, message_id, seq, assigned_spu);
  END IF;
END
$constraints$;

-- 旧的无 SPU 写入接口仍按原三列幂等；该索引不约束 v3 fan-out 行。
CREATE UNIQUE INDEX IF NOT EXISTS ux_unclassified_legacy_key
  ON public.voc_unclassified_evidence (message_id, seq, week)
  WHERE run_id IS NULL;
CREATE INDEX IF NOT EXISTS ix_terminal_ledger_run
  ON public.voc_unclassified_evidence
     (run_id, assigned_spu, message_id, seq)
  WHERE run_id IS NOT NULL;

COMMENT ON COLUMN public.voc_unclassified_evidence.terminal_id IS
  '终态账技术主键；035 前的存量行也保留并自动取得该值。';
COMMENT ON COLUMN public.voc_unclassified_evidence.run_id IS
  'v3 终态所属归属快照 run_id；035 前存量行为 NULL。';
COMMENT ON COLUMN public.voc_unclassified_evidence.assigned_spu IS
  'v3 终态对应的冻结 SPU；与 run_id 同空，035 前存量行为 NULL。';
COMMENT ON TABLE public.voc_unclassified_evidence IS
  'Stage1/生成/grounding 已知终态账；v3 粒度为 run_id + 快照扇出键。';

DO $selfcheck$
DECLARE
  bad_pair_rows bigint;
  duplicate_terminal_keys bigint;
BEGIN
  SELECT count(*) INTO bad_pair_rows
    FROM public.voc_unclassified_evidence
   WHERE (run_id IS NULL) IS DISTINCT FROM (assigned_spu IS NULL)
      OR (run_id IS NOT NULL AND reason IS NULL);

  SELECT count(*) INTO duplicate_terminal_keys
    FROM (
      SELECT run_id, message_id, seq, assigned_spu
        FROM public.voc_unclassified_evidence
       WHERE run_id IS NOT NULL
       GROUP BY run_id, message_id, seq, assigned_spu
      HAVING count(*) > 1
    ) duplicated;

  IF bad_pair_rows <> 0 OR duplicate_terminal_keys <> 0 THEN
    RAISE EXCEPTION
      '035 自检失败：run/SPU 配对异常=%，v3 终态重复键=%',
      bad_pair_rows, duplicate_terminal_keys;
  END IF;
END
$selfcheck$;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.voc_unclassified_evidence TO voc_writer;
GRANT USAGE, SELECT
  ON SEQUENCE public.voc_unclassified_evidence_terminal_id_seq TO voc_writer;
REVOKE INSERT, UPDATE, DELETE
  ON public.voc_unclassified_evidence FROM voc_human, voc_reader;
GRANT SELECT
  ON public.voc_unclassified_evidence TO voc_human, voc_reader;

COMMIT;
